run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  gocyclo:
    min-complexity: 20
  goconst:
    min-len: 3
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  misspell:
    locale: US
  lll:
    line-length: 150
  funlen:
    lines: 120
    statements: 60
  gocognit:
    min-complexity: 25
  nestif:
    min-complexity: 8
  mnd:
    settings:
      mnd:
        checks: argument,case,condition,operation,return,assign
  dupl:
    threshold: 150

linters:
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nestif
    - prealloc
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - goconst
        - dupl
        - funlen
    - path: internal/handlers/
      linters:
        - gocyclo
        - funlen
        - dupl
    - path: internal/services/
      linters:
        - gocyclo
        - funlen
    - path: internal/repository/
      linters:
        - rowserrcheck
        - errcheck
    - path: main.go
      linters:
        - lll
        - gocritic
    - text: "cancelled"
      linters:
        - misspell
    - text: "CANCELLED"
      linters:
        - misspell
  max-issues-per-linter: 0
  max-same-issues: 0